# Generated by Django 5.0 on 2024-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prority',
            new_name='priority',
        ),
    ]
